name: Node.js Package

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  max-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:max
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  dist-push:
    needs: max-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:max
      - name: Push dist to dist branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout --orphan dist
          git rm -rf .
          mv dist/* .
          git add .
          git commit -m "CI: update dist [skip ci]"
          git push --force origin dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
