name: Node.js Package

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - master

jobs:
  max-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --legacy-peer-deps
      - run: npm install -g @umijs/max
      - run: max build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  dist-push:
    needs: max-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: artifact/
      - name: Clean and Force Push dist
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout master
          git pull origin master

          # 清除仓库原有的 dist 内容
          if [ -d dist ]; then
            git rm -rf dist
            git commit -m "CI: clean old dist [skip ci]" || echo "No old dist to clean"
          fi

          # 拷贝新的 dist
          cp -r artifact/dist /home/runner/work/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}/dist

          # 强制添加新的 dist
          git add -f dist
          git commit -m "CI: update dist [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push -f origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
